#!/bin/bash

p=/tmp/nusortinput.$$

mkfifo $p

out="$NWORK_FILE"

# | grep --line-buffered -ao		\
# 	'@\]52;c;[0-9A-Za-z+/]*=*$'	\

<$p tr '\033\007' '@\n'			\
| sed -u 				'
	/.*@]52;c;\([0-9a-zA-Z+\/]*=*\)$/!d
	s,,( echo \1 | base64 -d; echo ) >>'$out',
'					\
| /bin/sh				&

. `dirname $0`/my_nusort_config | tee $p
