#!/bin/sh

`dirname $0`/../nusort or	\
| grep -o '\<[0-f]\{4\}$'	\
| sort > /tmp/curren.$$

`dirname $0`/missingwithpri	\
| grep -ow '[CVZ][0-f]\{4\}'	\
| sed 's/.//'			\
| sort > /tmp/extras.$$

comm /tmp/curren.$$ /tmp/extras.$$ -13	\
| sed 's/\(..\)\(..\)/\2 \1/'		\
| sort -r				\
| awk					'
!f[$2] {
	printf "%02s%02s\n", $2, $1;
	f[$2] = 1;
}'
