#!/bin/sh

test -e addme && exit

allns						\
| grep -ow [CVZ]'[0-f]\{4\}\|[0-f]\{4\}$'	\
| sed						'
	s/^\(..\)\(..\)$/\1 \2 ~/
	s/\([CVZ]\)\(..\)\(..\)/\2 \3 \1/
'						\
| sort -u -r					\
| awk						'
BEGIN { sep = "" }

/[CVZ]/ {
	if (!f[$1 ""]) {
		printf "%s[CVZ]%s%s", sep, $1, $2;
		sep = "\\|";
	}
}

{ f[$1 ""] = 1; }'				\
| tee /tmp/rsc.$$				\
| xargs -0 ~/nusort/u/missingwithpri		>addme
