#!/bin/sh

export LC_ALL=C

test -f addme || exit 1

if ! test -f before.db; then
	( cd ~/nusort; ~/nusort/nusort or ) >before.db || exit 1
fi
if ! test -f mix.db; then
	(
		cat before.db
		<addme sed '
			s/^"*\([^", ]*\)"*,* /\t{"\1", /
			s/+$//
			s/ ?,/ #,/
		'
	)					\
	| LC_ALL=C sort -k 6 -k 3,3r -k 1,1	\
	>mix.db
fi

test -f after.db ||
<mix.db awk -F, '
BEGIN { OFS="," }
{
	if ($3 == " #") {
		if (pri != ($6 "")) $3 = " 1"; else $3 = " 0";
	}
	pri = ($6 "");
	$6 = "";
	print;
}' >after.db

test -f newresid ||
<mix.db sed 's/.*}, //' | sort -u | sed '
	s/..//
	s/.*/0x&,/
	s/^0x00/@&/
' | tr -d '\n' | tr @ '\n' >newresid
