#!/bin/sh

export LC_ALL=C

test -f addme || exit 1

ksort () {
	sort -k 6 -k 3,3r -k 1,1 "$@"
}

make -C ~/nusort nusort || exit 1

if ! test -f before.db; then
	( cd ~/nusort; ~/nusort/nusort or ) >before.db || exit 1
fi
if ! test -f mix.db; then
	(
		cat before.db
		<addme tr -d '' | sed '
			s/^"*\([^", ]*\)"*,* /\t{"\1", /
			s/+$//
		'
	) | sed 's/\(, [ 0-9]\{5\}, \)[0?],/\1#,/' | ksort >mix.db
fi

test -f after.db ||
<mix.db awk -F, '
BEGIN { OFS="," }
{
	if ($3 == " #") {
		if (pri != ($6 "")) $3 = " 1"; else $3 = " 0";
	}
	pri = ($6 "");
	$6 = ""; # sed s/, [0-f]\{4\}$/,/
	print;
}' >after.db

test -f newresid ||
<mix.db sed 's/.*}, //' | sort -u | sed '
	s/..//
	s/.*/0x&,/
	s/^0x00/@&/
' | tr -d '\n' | tr @ '\n' >newresid
