#!/bin/sh

test -e addme && exit

ndir=$HOME/nusort

$ndir/u/allji					\
| grep -ow [CVZ]'[0-f]\{4\}\|[0-f]\{4\}$'	\
| sed '
	s/^\(....\)$/\1 ~/
	s/\([CVZ]\)\(....\)/\2 \1/
'						\
| LC_ALL=C sort -r -u				\
| awk '
	BEGIN { sep = "" }

	/[CVZ]/ {
		if (!f[$1 ""]) {
			printf "%s[CVZ]%s", sep, $1;
			sep = "\\|";
		}
	}

	{ f[$1 ""] = 1; }
' >/tmp/mrsc.$$

if test 0 = `wc -c </tmp/mrsc.$$`; then
	cat
else
	xargs -0 $ndir/u/missingwithpri
fi </tmp/mrsc.$$ >addme
